FROM node:23-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package.json package-lock.json ./
COPY server/package.json server/
COPY client/package.json client/

RUN npm install

COPY server/ server/
COPY client/ client/

EXPOSE 3000 3001

CMD ["npm", "run", "dev"]
